name: "ci-tain"

on:
  push:
    branches:
    - main


jobs:

  my_job:
    runs-on: ubuntu-18.04


    steps:
    - uses: actions/checkout@v1
    # - name: test
    #   run: | 
    #     whoami
    #     pwd
    #     sudo ls -la /
    - name: install nginx and configurate
      run: | 
        sudo apt update
        sudo apt install nginx curl -y
        sudo cp ./.github/files/site.conf /etc/nginx/sites-available/site.conf
        nginx -s reload
        nginx -g daemon off;
    - name: curl index.html
      run: curl http://127.0.0.1/
