name: "ci-tain"

on:
  push:
    branches:
    - main


jobs:

  my_job:
    runs-on: ubuntu-18.04


    steps:
    - uses: actions/checkout@v1
    - name: install nginx and configurate
      run: | 
        apt update
        apt install nginx curl -y
        cp ./.github/files/site.conf /etc/nginx/sites-available/site.conf
    - name: curl index.html
      run: curl http://127.0.0.1/
