name: "ci-tain"

on:
  push:
    branches:
    - main


jobs:

  my_job:
    runs-on: ubuntu-18.04


    steps:
    - uses: actions/checkout@v1
    # - name: test
    #   run: | 
    #     whoami
    #     pwd
    #     sudo ls -la /
    - name: update apt
      run: sudo apt update 
    - name: install nginx and curl
      run: sudo apt install nginx curl -y
    - name: copy file config
      run: sudo cp ./.github/files/site.conf /etc/nginx/sites-available/site.conf
    - name: nginx start
      run: |
        sudo nginx -s start
        sudo nginx -g daemon off;
    - name: curl index.html
      run: curl http://127.0.0.1/
